[project]
name = "truenascharts-updater"
version = "0.1.0"
description = "Simple image tag updater for TrueNASCharts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]


